---
driver:
  name: vagrant
  network:
  - - forwarded_port
    - guest: 5555
      host: 5555
      auto_correct: true

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
# - name: centos-6.4

suites:
- name: default
  run_list:
  - recipe[chef_scout_realtime]
  attributes: {}
